#!/usr/bin/env bash

# Throttle bandwidth on OS X
# Useful for testing. Pass 0 as an argument to stop.

if [ "$1" = "0" ]; then
  echo "Stopping bandwidth throttling."
  sudo ipfw delete 1
else
  echo "Throttling bandwith to $1KByte/s."
  sudo ipfw pipe 1 config bw $1KByte/s 
  sudo ipfw add 1 pipe 1 src-port 80
fi
