#!/usr/bin/env bash

# Search a directory recursively for search pattern ($1)
# TODO: Add other filetypes
grep -n "$1" $(find . -name *.rb -or -name *.erb -or -name *.yml -or -name *.js -or -name *.css -or -name *.haml -or -name *.sass -or -name *.conf | grep -v '\.git')
